### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager)

### ISSUE THREAD

**Issue by quangpaypay** [mapbox/mapbox-maps-android#1173]
## Environment

- Android OS version: Tested on Android 10
- Devices affected: Both the real device and emulator
- Maps SDK Version: v10.3.0

## Observed behavior and steps to reproduce

- Dependences: Only using `com.mapbox.maps:android:10.3.0`.
- Then, we initialized the map programmatically like this.
```kotlin
val mapView: MapView by lazy {
   ResourceOptionsManager.getDefault(context = context, context.getString(R.string.map_mapbox_access_token))
   MapView(context = context)
}
```
- The the error happened with the following logs
```
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager) (tried Java_com_mapbox_maps_assets_AssetManagerProvider_initialize and Java_com_mapbox_maps_assets_AssetManagerProvider_initialize__Landroid_content_res_AssetManager_2)
        at com.mapbox.maps.assets.AssetManagerProvider.initialize(Native Method)
        at com.mapbox.maps.MapController.<init>(MapController.kt:65)
        at com.mapbox.maps.MapView.<init>(MapView.kt:101)
        at com.mapbox.maps.MapView.<init>(MapView.kt:52)
        at com.mapbox.maps.MapView.<init>(MapView.kt:52)
```

Thank you!

**Comment by Chaoba** [comment]
@quangpaypay Thanks for reporting.
Can you provide more details on which device and emulator are affected?
Can you create a minimum project that can reproduce this?

**Comment by quangpaypay** [comment]
@Chaoba: Thanks for your quick response. 
I tested with the following devices.
- Real device: Samsung Galaxy SC-02K
- Emulator: Pixel 2 API 30.

**Comment by ZiZasaurus** [comment]
@quangpaypay, thank you for this additional information. As requested above, can you create a minimum project that reproduces this?

**Comment by quangpaypay** [comment]
@ZiZasaurus : Lets me prepare that.
In the meantime, if you have any suggestion or hint which relates to this issue. I would like to try too. Thanks. 🙏

**Comment by Chaoba** [comment]
@quangpaypay Are you using App bundle? If yes, maybe related to [mapbox/mapbox-gl-native-android#416](https://github.com/mapbox/mapbox-gl-native-android/issues/416)

**Comment by quangpaypay** [comment]
@Chaoba : We run the debug build which uses "Default APK".

**Comment by quangpaypay** [comment]
@Chaoba @ZiZasaurus : I would like to share some update.
We found that there is a conflict under our app configuration, so the native lib can not be loaded at the startup time.
The issue is fixed now, and thanks for your time. 🙏

**Comment by clownba0t** [comment]
Just in case anyone else runs into the same issue, the root cause for us was that we had disabled the AndroidX startup library's automatic initialisation provider, as documented [here](https://developer.android.com/topic/libraries/app-startup#disable-all).

> To disable all automatic initialization, remove the entire entry for InitializationProvider from the manifest:
> ```
> <provider
>    android:name="androidx.startup.InitializationProvider"
>    android:authorities="${applicationId}.androidx-startup"
>    tools:node="remove" />
> ```

For various reasons we were unable to restore the automatic initialisation provider, but were ultimately able to work around the issue by manually running the initialisation for Mapbox's automatic initialisation component via the `onCreate` override in our `Application` subclass. Something like this:

```kotlin
        AppInitializer.getInstance(this)
            .initializeComponent(MapboxMapsInitializer::class.java)
```

**Comment by yunikkk** [comment]
> For various reasons we were unable to restore the automatic initialisation provider

Hey, thanks for the details, could you please clarify what do you mean by that? Were you unable to add the InitializationProvider for some internal reasons or the issue still was present even with InitializationProvider enabled?

**Comment by yinxiucheng** [comment]
@quangpaypay .  Hi , I also encounter this error, could you write how you fixed it ?

**Comment by quangpaypay** [comment]
@yinxiucheng : I did the same thing as @clownba0t 's suggestion.
```kotlin
 AppInitializer.getInstance(this)
            .initializeComponent(MapboxMapsInitializer::class.java)
```

**Comment by 113408** [comment]
Just adding on this issue. If you face `java.lang.UnsatisfiedLinkError` Exception it might be because the Mapbox Initializer didn't launch as planned. You can either fix that through your manifest or from your Application class.
**Manifest Method:**
Replace this :
```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            tools:node="remove">
</provider>
 ```
With:
```
<provider
            android:name="androidx.startup.InitializationProvider"
            android:authorities="${applicationId}.androidx-startup"
            android:exported="false"
            tools:node="merge">
            <meta-data
                android:name="com.initializer.to.be.removed"
                android:value="androidx.startup"
                tools:node="remove" />
</provider>
```
**Code Method (described above):**
```
AppInitializer.getInstance(this)
            .initializeComponent(MapboxMapsInitializer::class.java)
```
