### ISSUE TITLE
i have crush about token but i already sync it -solved-

### ISSUE THREAD

**Issue by Sae-Ba** [mapbox/mapbox-maps-android#1205]
this is my Logcat

2022-03-06 21:01:57.826 25925-25925/com.tuk.tukproject1 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tuk.tukproject1, PID: 25925
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tuk.tukproject1/com.tuk.tukproject1.MainActivity}: android.view.InflateException: Binary XML file line #2 in com.tuk.tukproject1:layout/activity_main: Binary XML file line #2 in com.tuk.tukproject1:layout/activity_main: Error inflating class com.mapbox.maps.MapView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4031)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4197)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     Caused by: android.view.InflateException: Binary XML file line #2 in com.tuk.tukproject1:layout/activity_main: Binary XML file line #2 in com.tuk.tukproject1:layout/activity_main: Error inflating class com.mapbox.maps.MapView
     Caused by: android.view.InflateException: Binary XML file line #2 in com.tuk.tukproject1:layout/activity_main: Error inflating class com.mapbox.maps.MapView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:858)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1010)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:663)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.tuk.tukproject1.MainActivity.onCreate(MainActivity.kt:24)
        at android.app.Activity.performCreate(Activity.java:8282)
        at android.app.Activity.performCreate(Activity.java:8262)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4005)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4197)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
     Caused by: com.mapbox.maps.MapboxConfigurationException: Using MapView requires providing a valid access token when inflating or creating the view.
    Provide the token by either:
      1. Initialising the MapView programmatically using 'MapInitOptions' and configure the token using 'MapInitOptions.resourceOptions.accessToken'.
2022-03-06 21:01:57.826 25925-25925/com.tuk.tukproject1 E/AndroidRuntime:   2. Or by passing it using MapView's 'mapbox_resourcesAccessToken' XML attribute.
      3. Or by creating a mapbox_access_token string resource.
    The access token parameter is required when using a Mapbox service.
    Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
    More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
        at com.mapbox.maps.ResourceOptionsManager$Companion.getDefault(ResourceOptionsManager.kt:71)
        at com.mapbox.maps.ResourcesAttributeParser.parseResourcesOptions(ResourcesAttributeParser.kt:23)
        at com.mapbox.maps.MapView.parseTypedArray$sdk_release(MapView.kt:124)
        at com.mapbox.maps.MapView.<init>(MapView.kt:92)
        at com.mapbox.maps.MapView.<init>(MapView.kt:69)
        at com.mapbox.maps.MapView.<init>(MapView.kt:63)
        	... 27 more
2022-03-06 21:01:57.839 25925-25925/com.tuk.tukproject1 I/Process: Sending signal. PID: 25925 SIG: 9

`
import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.drawable.BitmapDrawable
import android.graphics.drawable.Drawable
import android.os.Bundle
import androidx.annotation.DrawableRes
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.content.res.AppCompatResources
import com.mapbox.geojson.Point
import com.mapbox.maps.MapView
import com.mapbox.maps.Style
import com.mapbox.maps.plugin.annotation.annotations
import com.mapbox.maps.plugin.annotation.generated.PointAnnotationOptions
import com.mapbox.maps.plugin.annotation.generated.createPointAnnotationManager

class MainActivity : AppCompatActivity() {
    private var mapView: MapView? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        mapView = findViewById(R.id.mapView)
        mapView?.getMapboxMap()?.loadStyleUri(
            Style.MAPBOX_STREETS,
            object : Style.OnStyleLoaded {
                override fun onStyleLoaded(style: Style) {
                    addAnnotationToMap()
                }
            }
        )
    }

    private fun addAnnotationToMap() {
// Create an instance of the Annotation API and get the PointAnnotationManager.
        bitmapFromDrawableRes(
            this@MainActivity,
            R.drawable.red_marker
        )?.let {
            val annotationApi = mapView?.annotations
            val pointAnnotationManager = annotationApi?.createPointAnnotationManager(mapView!!)
// Set options for the resulting symbol layer.
            val pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
// Define a geographic coordinate.
                .withPoint(Point.fromLngLat(18.06, 59.31))
// Specify the bitmap you assigned to the point annotation
// The bitmap will be added to map style automatically.
                .withIconImage(it)
// Add the resulting pointAnnotation to the map.
            pointAnnotationManager?.create(pointAnnotationOptions)
        }
    }
    private fun bitmapFromDrawableRes(context: Context, @DrawableRes resourceId: Int) =
        convertDrawableToBitmap(AppCompatResources.getDrawable(context, resourceId))

    private fun convertDrawableToBitmap(sourceDrawable: Drawable?): Bitmap? {
        if (sourceDrawable == null) {
            return null
        }
        return if (sourceDrawable is BitmapDrawable) {
            sourceDrawable.bitmap
        } else {
// copying drawable object to not manipulate on the same reference
            val constantState = sourceDrawable.constantState ?: return null
            val drawable = constantState.newDrawable().mutate()
            val bitmap: Bitmap = Bitmap.createBitmap(
                drawable.intrinsicWidth, drawable.intrinsicHeight,
                Bitmap.Config.ARGB_8888
            )
            val canvas = Canvas(bitmap)
            drawable.setBounds(0, 0, canvas.width, canvas.height)
            drawable.draw(canvas)
            bitmap
        }
    }
}`

`<com.mapbox.maps.MapView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:mapbox="http://schemas.android.com/apk/res-auto"
    android:id="@+id/mapView"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    mapbox:mapbox_cameraTargetLat="59.31"
    mapbox:mapbox_cameraTargetLng="18.06"
    mapbox:mapbox_cameraZoom="9.0"
    />`

Will I be able to get help?
I hope to run https://docs.mapbox.com/android/maps/examples/default-point-annotation/ 
this example but it doesn't work..

App just runs less than 1sec with black window and shutdown

Mapbox 10.3.0
Gradle ver 7.2
AndroidStudio 2021.1.1.22

**Comment by Sae-Ba** [comment]
(https://medium.com/@alessandro.lombardi.089/setting-up-mapbox-sdk-10-1-0-in-android-studio-2021-5083ca876bdd)
now i fixed it ...

**Comment by ZiZasaurus** [comment]
@Sae-Ba, happy you were able to get this resolved!

**Comment by limingchina** [comment]
@Sae-Ba , I still can't solve the issue. I checked your article. What you did is only adding the string resource to your project. However, it looks to me one has to fetch that string and use it in the source code. 

I also checked the mapbox SDK implementation, the code in ResourcesAttributeParser.kt.
`    val token = typedArray.getString(R.styleable.mapbox_MapView_mapbox_resourcesAccessToken)
    val builder = ResourceOptionsManager.getDefault(context, token).resourceOptions.toBuilder()
`
seems to handle the token automatically. However, I can't get it to work. 
I've added the entry in the activity_main.xml which contains the mapbox's mapview.
`<com.mapbox.maps.MapView        mapbox:mapbox_resourcesAccessToken="mytoken"
`
However, this still doesn't work. @ZiZasaurus , any idea?

**Comment by RajanLad** [comment]
i know its late but you can follow the following. if you want different or dynamic token. other than token from strings.xml

MapView(this,MapInitOptions(this,MapInitOptions(this).resourceOptions.toBuilder().accessToken(BuildConfig.MAPBOX_TOKEN).build()))

use this at MainApplication or MainActivity.

but don't remove or comment

<string name="mapbox_access_token"></string>

just keep it empty
