### ISSUE TITLE
[Mapbox-SDK v9.5.0] Missing dependencies

### ISSUE THREAD

**Issue by henryx27** [mapbox/mapbox-maps-android#1285]
## Environment

- Android OS version: N/A
- Devices affected: N/A
- Maps SDK Version: 9.5.0

## Observed behavior and steps to reproduce

Attempt to build application with dependency on `mapboxsdk-android-sdk:9.5.0`

`build.gradle` is configured as follows:
```
        maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = 'mapbox'
                // Use the secret token you stored in gradle.properties as the password
                password = keystoreProperties['mapboxToken'] ?: ""
            }
        }
```
where the `password` is a valid token

## Expected behavior

Dependencies are downloaded and build passes

## Notes / preliminary analysis

Gradle error as follows:

```
Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Required by:
         project :core > com.mapbox.mapboxsdk:mapbox-android-sdk:9.5.0
```

Attempts to view download artifact directly result in:
```
"No object on S3: v2/com-mapbox-mapboxsdk-mapbox-android-accounts/releases/android/0.7.0/maven/mapbox-android-accounts-0.7.0.aar"
```

**Comment by joshrvezy** [comment]
im running into the same issue with mapbox 9.7.1

**Comment by joshrvezy** [comment]
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - https://dl.google.com/dl/android/maven2/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - https://zendesk.jfrog.io/zendesk/repo/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - http://oss.sonatype.org/content/repositories/snapshots/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - https://appboy.github.io/appboy-android-sdk/sdk/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
     Required by:
         project :app > com.mapbox.mapboxsdk:mapbox-android-sdk:9.7.1

**Comment by mysport12** [comment]
We are experiencing the same and Friday was the last day we had a successful build.

**Comment by mattijsf** [comment]
We ran into the same problem since the past couple of hours:

```
> Could not resolve all artifacts for configuration ':app:developmentDebugRuntimeClasspath'.
   > Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0.
     Searched in the following locations:
       - file:/home/circleci/.m2/repository/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
       - https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.pom
....
```

Probable caused by some degraded performance mentioned on: https://status.mapbox.com/
> [Elevated API Errors](https://status.mapbox.com/incidents/lfycsrc2f85j)
Identified - We're experiencing an elevated level of API errors and are currently looking into the issue.
Apr 19, 03:05 UTC

**Comment by ank27** [comment]
@henryx27 Thank you. We are currently looking into it and will update as soon as it's fixed.

**Comment by limingchina** [comment]
Issue seems to be fixed. Can anyone else confirm?

**Comment by mattijsf** [comment]
@limingchina I can confirm. Our builds are also succeeding again since today.

**Comment by ank27** [comment]
@limingchina @henryx27 Yes, Confirming that the issue is fixed and the build will be success now. 
Closing this ticket, Feel free to reopen if you are unable to build the project.

Thank you :)

**Comment by Anil-dhiman** [comment]
hello @ank27  i am unable to build my project as I have download this https://github.com/mapbox/mapbox-navigation-android for reference project but i cant able to build it because it is also showing same error which i facing in my personal project when i add dependency and try to build my project. it my 4th day on this issue. i don't get any solution and idea nothing from anywhere.
Mostly tried all the possible solution but still not working. you documentation. i am working for android.
Also i have mailed to your technical support team and i don't get a single reply from them. i have purchased your maps SDK and there is zero technical support facility they are providing. Now i am stuck because of dependency failure issue i am facing.

steps which i followed-
- added token in gradle.properties  "MAPBOX_TOKEN"
- added these in build.gradle project level
- maven {
            url 'https://api.mapbox.com/downloads/v2/releases/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                // Do not change the username below.
                // This should always be `mapbox` (not your username).
                username = "mapbox"
                // Use the secret token you stored in gradle.properties as the password
                password = MAPBOX_DOWNLOADS_TOKEN
            }
        }
        maven {
            url 'https://api.mapbox.com/downloads/v2/snapshots/maven'
            authentication {
                basic(BasicAuthentication)
            }
            credentials {
                username = "mapbox"
                password = MAPBOX_DOWNLOADS_TOKEN
            }
       
> }

 -   implementation "com.mapbox.navigation:android:2.3.0"
//    implementation "com.mapbox.navigation:android:2.9.0"

still not able to resolve this issue please help me.


error:
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.mapbox.navigation:android:2.3.0.

Please help me let me know any solution

**Comment by badredaha** [comment]
its not fixed ? I get Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0 today

**Comment by cankarabey** [comment]
> its not fixed ? I get Could not find com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0 today

same issue here, could be related to jcenter shutting down today

**Comment by GunnarMM** [comment]
`mapbox-android-accounts` is not present on JCenter.

See: https://repo1.maven.org/maven2/com/mapbox/mapboxsdk/

Our app is using Mapbox v8. Anyone using v10 and still experiencing this issue?

**Comment by 5PK** [comment]
I'm experiencing this when building for android, works fine for ios

`Could not find com.mapbox.maps:android:10.1.3.
[RUN_GRADLEW]      Required by:
[RUN_GRADLEW]          project :rnmapbox_maps`

**Comment by srmncnk** [comment]
Anyone else experiencing this today?

**Comment by programmin1** [comment]
I also have

org.gradle.internal.resolve.ArtifactNotFoundException: Could not find mapbox-android-accounts-0.7.0.aar (com.mapbox.mapboxsdk:mapbox-android-accounts:0.7.0).

on an old Mapbox 9 build. Can they bring back the library for those of us with some older app builds...?

**Comment by flasher297** [comment]
We don't support old v9 maps anymore.
If you still use v10, you can try to update to the latest release
https://github.com/mapbox/mapbox-maps-android/releases/tag/v10.18.4

**Comment by srmncnk** [comment]
@flasher297 For what it's worth, this only forces people to consider migrating to maplibre, since migration to that project is by far easier than to v10.

**Comment by flasher297** [comment]
@srmncnk this binary was not removed by us, it's not available anymore because of the shutdown of Jcenter.
 But I've doublechecked and see that this dependency is available at Mapbox Maven:
 `https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.aar`
 You can set up access with your credentials - More info's [here](https://docs.mapbox.com/android/maps/guides/install/#part-2-add-the-dependency).

**Comment by srmncnk** [comment]
Thank you for this.

**Comment by programmin1** [comment]
https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-android-accounts/0.7.0/mapbox-android-accounts-0.7.0.aar gives a 401 response in Android Studio - and a 403 when the proper public token of your account is added in the maven { } configuration.

**Comment by programmin1** [comment]
My mistake, password: token in the mapbox { } definition should be not default token but a token with DOWNLOAD permission.
