### ISSUE TITLE
IllegalArgumentException missing a comma or '}' after an object member

### ISSUE THREAD

**Issue by brendanw** [mapbox/mapbox-maps-android#2004]
## Environment

- Android OS version: 13
- Devices affected: Pixel 5
- Maps SDK Version: 10.9.0

## Observed behavior and steps to reproduce

Mapbox map occasionally throws uncaught IllegalStateException. This does not happen consistently.

Error stacktrace

```
java.lang.IllegalArgumentException: Parse error at offset 46: Missing a comma or '}' after an object member.
        at com.mapbox.maps.StyleManager.addPersistentStyleLayer(StyleManager.java:-2)
        at com.mapbox.maps.NativeMapImpl.addPersistentStyleLayer(NativeMapImpl.kt:273)
        at com.mapbox.maps.Style.addPersistentStyleLayer(Style.kt:838)
        at com.mapbox.maps.plugin.locationcomponent.LocationLayerWrapper.bindTo(LocationLayerWrapper.kt:21)
        at com.mapbox.maps.plugin.locationcomponent.LocationComponentPositionManager.addLayerToMap(LocationComponentPositionManager.kt:30)
        at com.mapbox.maps.plugin.locationcomponent.LocationIndicatorLayerRenderer.addLayers(LocationIndicatorLayerRenderer.kt:35)
        at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager.initialize(LocationPuckManager.kt:103)
        at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl$activateLocationComponent$1.invoke(LocationComponentPluginImpl.kt:207)
        at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl$activateLocationComponent$1.invoke(LocationComponentPluginImpl.kt:184)
        at com.mapbox.maps.plugin.MapDelegateProviderImpl.getStyle$lambda-0(MapDelegateProviderImpl.kt:21)
        at com.mapbox.maps.plugin.MapDelegateProviderImpl.$r8$lambda$prB63jRkHNgIjSUbBTljg7oBEc8(MapDelegateProviderImpl)
        at com.mapbox.maps.plugin.a.onStyleLoaded(Unknown:2)
        at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:355)
        at com.mapbox.maps.plugin.MapDelegateProviderImpl.getStyle(MapDelegateProviderImpl.kt:21)
        at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl.activateLocationComponent(LocationComponentPluginImpl.kt:184)
        at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl.applySettings(LocationComponentPluginImpl.kt:358)
        at com.mapbox.maps.plugin.locationcomponent.generated.LocationComponentSettingsBase.updateSettings(LocationComponentSettingsBase.kt:39)
```

## Expected behavior

Mapbox library should not randomly throw uncaught IllegalStateException.

## Notes / preliminary analysis

This crash happens the first time I load the activity which hosts the mapbox map. Usually if I open the same activity a second time, I don't see the issue. Here is the complete source code for the hosting activity

```
package com.basebeta.exit.map

import android.app.Activity
import android.content.Context
import android.content.Intent
import android.os.Bundle
import androidx.appcompat.content.res.AppCompatResources
import com.basebeta.App
import com.basebeta.AppDependencies
import com.basebeta.BaseBetaActivity
import com.basebeta.R
import com.basebeta.analytics.AE
import com.basebeta.databinding.TerrainMapBinding
import com.basebeta.db.Exit
import com.basebeta.exit.ExitActivity
import com.basebeta.utility.getCameraHeading
import com.basebeta.utility.views.AnimUtils
import com.mapbox.geojson.FeatureCollection
import com.mapbox.geojson.Point
import com.mapbox.maps.CameraOptions
import com.mapbox.maps.MapInitOptions
import com.mapbox.maps.MapOptions
import com.mapbox.maps.MapView
import com.mapbox.maps.ResourceOptions
import com.mapbox.maps.extension.style.expressions.dsl.generated.interpolate
import com.mapbox.maps.extension.style.layers.addLayer
import com.mapbox.maps.extension.style.layers.generated.circleLayer
import com.mapbox.maps.extension.style.sources.addSource
import com.mapbox.maps.extension.style.sources.generated.geoJsonSource
import com.mapbox.maps.plugin.LocationPuck2D
import com.mapbox.maps.plugin.Plugin.*
import com.mapbox.maps.plugin.locationcomponent.location
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okio.FileSystem
import okio.Path.Companion.toPath
import okio.buffer
import okio.source
import timber.log.Timber
import java.io.File


class TerrainMapActivity : BaseBetaActivity() {
   lateinit var exitId: String

   private lateinit var binding: TerrainMapBinding
   private var mapView: MapView? = null

   override fun onCreate(savedInstanceState: Bundle?) {
      super.onCreate(savedInstanceState)
      binding = TerrainMapBinding.inflate(layoutInflater)

      App.analytics.trackEvent(AE.VIEW_TERRAIN_MAP)

      exitId = intent.getStringExtra(ExitActivity.KEY_EXIT_ID)!!
      val exit = AppDependencies.exitRepository.getExit(exitId) ?: run {
         throw IllegalStateException("No exit found for exitId $exitId")
      }

      val myResourceOptions = ResourceOptions.Builder()
         .accessToken("REDACTED")
         .build()

      val initialCameraOptions = CameraOptions.Builder()
         .center(Point.fromLngLat(exit.latLng.longitude, exit.latLng.latitude))
         .pitch(75.0)
         .zoom(15.5)
         .bearing(getCameraHeading(exit.jumpMetrics.exitDirection))
         .build()

      val mapOptions = MapOptions.Builder()
         .optimizeForTerrain(true)
         .build()

      val mapInitOptions = MapInitOptions(
         context = this,
         resourceOptions = myResourceOptions,
         cameraOptions = initialCameraOptions,
         mapOptions = mapOptions,
         styleUri = "mapbox://styles/basebeta/cla1us0xn000314mob3xabfm2"
      )

      mapView = MapView(this, mapInitOptions = mapInitOptions)
      setContentView(binding.root)
      binding.headerTitle.text = exit.name
      binding.root.addView(mapView)

      if (exit.gpsTracks != null && exit.gpsTracks!!.geojson.isNotEmpty()) {
         loadGeoJson(exit)
      }

      setupLocationTracking(mapView!!)
   }

   private fun loadGeoJson(exit: Exit) {
      //attempt to load geojson
      val map = mapView!!.getMapboxMap()
      val gpsCache = AppDependencies.gpsCache
      GlobalScope.launch {
         val rawJson = withContext(Dispatchers.IO) {
            if (!gpsCache.updateCacheIfNecessary(exit.gpsTracks!!.geojson)) {
               return@withContext null
            }

            val androidPath = gpsCache.androidAbsolutePath(exit.gpsTracks!!.geojson)
            if (!FileSystem.SYSTEM.exists(androidPath.toPath())) {
               return@withContext null
            }

            val source = File(androidPath).source().buffer()
            val result = source.readUtf8()
            source.close()
            result
         } ?: return@launch

         map.getStyle { style ->
            val SOURCE_ID = "my_source_id"
            val geoJsonSource = geoJsonSource(SOURCE_ID) {
               val featureCollection = FeatureCollection.fromJson(rawJson)
               featureCollection(featureCollection)
            }

            val LAYER_ID = "my_layer_id"
            /*val lineLayer = lineLayer(LAYER_ID, SOURCE_ID) {
               lineColor(ContextCompat.getColor(this@TerrainMapActivity, R.color.red))
               lineWidth(10.0)
            }*/

            val circleLayer = circleLayer(LAYER_ID, SOURCE_ID) {
               circleColor(getColor(R.color.red))
            }

            Timber.d("adding approach red line layer")
            style.addSource(geoJsonSource)
            style.addLayer(circleLayer)

            // see https://github.com/mapbox/mapbox-maps-android/issues/1474
            mapView!!.location.updateSettings {
               enabled = true
               pulsingEnabled = true
            }
         }
      }
   }

   private fun setupLocationTracking(mapView: MapView) {
      mapView.location.locationPuck = LocationPuck2D(
         topImage = AppCompatResources.getDrawable(
            this,
            com.mapbox.maps.plugin.locationcomponent.R.drawable.mapbox_user_icon
         ),
         bearingImage = AppCompatResources.getDrawable(
            this,
            com.mapbox.maps.plugin.locationcomponent.R.drawable.mapbox_user_bearing_icon
         ),
         shadowImage = AppCompatResources.getDrawable(
            this,
            com.mapbox.maps.plugin.locationcomponent.R.drawable.mapbox_user_stroke_icon
         ),
         scaleExpression = interpolate {
            linear()
            zoom()
            stop {
               literal(0.0)
               literal(0.6)
            }
            stop {
               literal(20.0)
               literal(1.0)
            }
         }.toJson()
      )
   }

   companion object {
      const val KEY_EXIT_ID = "key_exit_id"

      fun launch(context: Context, exitId: String) {
         val intent = Intent(context, TerrainMapActivity::class.java)
         intent.putExtra(KEY_EXIT_ID, exitId)
         context.startActivity(intent)
         AnimUtils.setTransition(context as Activity, AnimUtils.Side.BOTTOM, false)
      }
   }
}
```

## Additional links and references

No other videos or traces.

**Comment by ank27** [comment]
Hi, this was fixed in v10.10 or newer version. Could you try upgrading to v10.10.1 or v10.11.0, and let us know if it works. 
Thank you.

**Comment by brendanw** [comment]
Testing w/  `com.mapbox.maps:android:10.10.1`, I still see the crash, albeit with moved line number

```
java.lang.IllegalArgumentException: Parse error at offset 124: Missing a comma or '}' after an object member.
                                                                                                    	at com.mapbox.maps.StyleManager.addPersistentStyleLayer(Native Method)
                                                                                                    	at com.mapbox.maps.NativeMapImpl.addPersistentStyleLayer(NativeMapImpl.kt:273)
                                                                                                    	at com.mapbox.maps.Style.addPersistentStyleLayer(Style.kt:840)
```

Testing on `com.mapbox.maps:android:10.11.0`, I still see crash:

```
                     java.lang.IllegalArgumentException: Parse error at offset 46: Missing a comma or '}' after an object member.
                                                                                                    	at com.mapbox.maps.StyleManager.addPersistentStyleLayer(Native Method)
                                                                                                    	at com.mapbox.maps.NativeMapImpl.addPersistentStyleLayer(NativeMapImpl.kt:272)
                                                                                                    	at com.mapbox.maps.Style.addPersistentStyleLayer(Style.kt:877)
                                                                                                    	at com.mapbox.maps.plugin.locationcomponent.LocationLayerWrapper.bindTo(LocationLayerWrapper.kt:21)
                                                                                                    	at com.mapbox.maps.plugin.locationcomponent.LocationComponentPositionManager.addLayerToMap(LocationComponentPositionManager.kt:30)
                                                                                                    	at com.mapbox.maps.plugin.locationcomponent.LocationIndicatorLayerRenderer.addLayers(LocationIndicatorLayerRenderer.kt:35)
                                                                                                    	at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager.initialize(LocationPuckManager.kt:103)
                                                                                                    	at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager$updateSettings$1.invoke(LocationPuckManager.kt:140)
                                                                                                    	at com.mapbox.maps.plugin.locationcomponent.LocationPuckManager$updateSettings$1.invoke(LocationPuckManager.kt:139)
```

**Comment by brendanw** [comment]
Playing around w/ the latest version `10.11.0` more. Moving the `updateSetting` call to be within the `setupLocationTracking` function defined in the example in the original issue resolves the crash:

```
   private fun setupLocationTracking(mapView: MapView) {
      mapView.location.locationPuck = LocationPuck2D(
         topImage = AppCompatResources.getDrawable(
            this,
            com.mapbox.maps.plugin.locationcomponent.R.drawable.mapbox_user_icon
         ),
         bearingImage = AppCompatResources.getDrawable(
            this,
            com.mapbox.maps.plugin.locationcomponent.R.drawable.mapbox_user_bearing_icon
         ),
         shadowImage = AppCompatResources.getDrawable(
            this,
            com.mapbox.maps.plugin.locationcomponent.R.drawable.mapbox_user_stroke_icon
         ),
         scaleExpression = interpolate {
            linear()
            zoom()
            stop {
               literal(0.0)
               literal(0.6)
            }
            stop {
               literal(20.0)
               literal(1.0)
            }
         }.toJson()
      )

      mapView.location.updateSettings {
         enabled = true
         pulsingEnabled = true
      }
   }
```

**Comment by brendanw** [comment]
I haven't seen this issue on mapbox v11+, so closing
