### ISSUE TITLE
Android app crashes with Fatal signal 11 error while rendering Mapbox map

### ISSUE THREAD

**Issue by ashishkharche** [mapbox/mapbox-maps-android#2052]

**Comment by kiryldz** [comment]
@ashishkharche hey, could you please share the style (and any runtime styling on top of it) you're using to get that crash?

**Comment by kiryldz** [comment]
> I get often fatal signal 11 error when navigating back and forth from various screen with mapbox view.
> 
> Here is the stask
> 
> ```
> art_sigsegv_fault 0x000074cbd3893520
> art::FaultManager::HandleFault(int, siginfo*, void*) 0x000074cbd3893a45
> art::SignalChain::Handler(int, siginfo*, void*) 0x000074ce74b86fcc
> __restore_rt 0x000074ce6fe94c00
> SkSurface_Base::getCachedCanvas() 0x000074ce6c4d9071
> android::uirenderer::StretchMask::draw(GrRecordingContext*, android::uirenderer::StretchEffect const&, SkRect const&, android::uirenderer::skiapipeline::SkiaDisplayList*, SkCanvas*) 0x000074ce6c64d33f
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400a76
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> SkDrawable::draw(SkCanvas*, SkMatrix const*) 0x000074ce6c4e26f1
> android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const 0x000074ce6c400e89
> android::uirenderer::skiapipeline::RenderNodeDrawable::onDraw(SkCanvas*) 0x000074ce6c64d7fa
> android::uirenderer::skiapipeline::SkiaPipeline::renderFrameImpl(SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, bool, android::uirenderer::Rect const&, SkCanvas*, SkMatrix const&) 0x000074ce6c4f5ba2
> android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, android::uirenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode> > > const&, android::uirenderer::FrameInfoVisualizer*) 0x000074ce6c4f193c
> android::uirenderer::renderthread::CanvasContext::draw() 0x000074ce6c46dea0
> std::__1::__function::__func<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0, std::__1::allocator<android::uirenderer::renderthread::DrawFrameTask::postAndWait()::$_0>, void ()>::operator()() (.__uniq.264041412789356548918088680803242235290.c1671e787f244890c877724752face20) 0x000074ce6c4ff58f
> android::uirenderer::renderthread::RenderThread::threadLoop() 0x000074ce6c5e0fe0
> android::Thread::_threadLoop(void*) 0x000074cbaeeb0780
> __pthread_start(void*) 0x000074ce6ff05d2b
> __start_thread 0x000074ce6fe99d38
> ```

This stacktrace is related to Android Render thread and not Mapbox Render thread. Please provide information from https://github.com/mapbox/mapbox-maps-android/issues/2052#issuecomment-1476202768 so that we could try to better understand what is going on.

**Comment by bhanuk-aidash** [comment]
Still facing the same crash when interacting with map view. 

Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 25041 (MapboxRenderThr), pid 24859 (.ivms_pro.debug)
---------------------------- PROCESS STARTED (25050) for package com.aidash.ivms_pro.debug ----------------------------
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone64_arm64/emulator64_arm64:12/SE1A.220203.002.A1/8151367:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2023-10-12 14:41:56.748304701+0530
Process uptime: 0s
Cmdline: com.aidash.ivms_pro.debug
pid: 24859, tid: 25041, name: MapboxRenderThr  >>> com.aidash.ivms_pro.debug <<<
uid: 10162
tagged_addr_ctrl: 0000000000000001
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
Cause: null pointer dereference
    x0  b40000754fc21178  x1  0000000000000010  x2  0000000000000190  x3  b4000075efb3c068
    x4  00000000000000ff  x5  0000000000000006  x6  0000000000000001  x7  b40000764fc51cd0
    x8  0000000000000001  x9  b40000754fc21140  x10 b40000756fa6c510  x11 0000000000000000
    x12 0000000000000000  x13 0000000000008b5e  x14 b4000075bfb03a30  x15 0000000000000001
    x16 00000074b6ff6340  x17 00000074b6e5c4e4  x18 00000074140d0000  x19 b40000754fc21178
    x20 b400007501279558  x21 b4000075efb3c068  x22 b4000075dfbd98e8  x23 00000074c2c76000
    x24 b4000075efb3bfe0  x25 0000000000017ffa  x26 0000000000000001  x27 b4000075efb3c5b8
    x28 b4000075efb3c5c0  x29 00000074c2c71790
    lr  0000007451b640c0  sp  00000074c2c71780  pc  0000007451b61e08  pst 0000000060001000
backtrace:
      #00 pc 0000000000507e08  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #01 pc 000000000050a0bc  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #02 pc 000000000052c444  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #03 pc 0000000000366ab8  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #04 pc 0000000000367af4  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #05 pc 0000000000362474  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #06 pc 00000000003609b0  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #07 pc 000000000037a588  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #08 pc 00000000003a3c38  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #09 pc 0000000000372f14  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #10 pc 00000000002b0f3c  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #11 pc 00000000002ac0ac  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #12 pc 000000000026cad0  /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!libmapbox-maps.so (BuildId: 97932236d497efd3)
      #13 pc 0000000000222244  /apex/com.android.art/lib64/libart.so (art_quick_generic_jni_trampoline+148) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #14 pc 0000000000213390  /apex/com.android.art/lib64/libart.so (nterp_helper+7712) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #15 pc 00000000003047a8  [anon:dalvik-classes33.dex extracted in memory from /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!classes33.dex]
      #16 pc 0000000000213390  /apex/com.android.art/lib64/libart.so (nterp_helper+7712) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #17 pc 000000000043150e  [anon:dalvik-classes33.dex extracted in memory from /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!classes33.dex]
      #18 pc 00000000002124c4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #19 pc 0000000000430226  [anon:dalvik-classes33.dex extracted in memory from /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!classes33.dex]
      #20 pc 00000000002124c4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #21 pc 0000000000430080  [anon:dalvik-classes33.dex extracted in memory from /data/app/~~fCPMINb1IcnJXoOzxy7KRg==/com.aidash.ivms_pro.debug-_IIj4TyV_PknJBPFicTzkA==/base.apk!classes33.dex]
      #22 pc 0000000002021098  /memfd:jit-cache (deleted) (android.view.Choreographer$CallbackRecord.run+232)
      #23 pc 0000000002018678  /memfd:jit-cache (deleted) (android.view.Choreographer.doCallbacks+680)
      #24 pc 000000000201c790  /memfd:jit-cache (deleted) (android.view.Choreographer.doFrame+1888)
      #25 pc 0000000002039a1c  /memfd:jit-cache (deleted) (android.view.Choreographer$FrameDisplayEventReceiver.run+172)
      #26 pc 000000000204f88c  /memfd:jit-cache (deleted) (android.os.Handler.handleCallback+140)
      #27 pc 0000000002039d58  /memfd:jit-cache (deleted) (android.os.Handler.dispatchMessage+104)
      #28 pc 000000000201d484  /memfd:jit-cache (deleted) (android.os.Looper.loopOnce+1348)
      #29 pc 000000000201ea48  /memfd:jit-cache (deleted) (android.os.Looper.loop+696)
      #30 pc 0000000000218be8  /apex/com.android.art/lib64/libart.so (art_quick_invoke_static_stub+568) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #31 pc 0000000000284224  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+216) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #32 pc 00000000003e34ac  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+400) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #33 pc 00000000003de320  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+804) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #34 pc 0000000000757de0  /apex/com.android.art/lib64/libart.so (MterpInvokeStatic+980) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #35 pc 0000000000203994  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_static+20) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #36 pc 0000000000422d7c  /system/framework/framework.jar
      #37 pc 00000000003d6150  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool)+304) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #38 pc 000000000073b6b8  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+776) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #39 pc 0000000000222378  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #40 pc 0000000000218964  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #41 pc 0000000000284208  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+188) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #42 pc 000000000061fb98  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #43 pc 000000000066e75c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1184) (BuildId: e6c658201ef1ec3760112fa1b838ab2c)
      #44 pc 00000000000b1910  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264) (BuildId: ba489d4985c0cf173209da67405662f9)
      #45 pc 00000000000513f0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ba489d4985c0cf173209da67405662f9)
---------------------------- PROCESS ENDED (24859) for package com.aidash.ivms_pro.debug ----------------------------
---------------------------- PROCESS STARTED (25057) for package com.aidash.ivms_pro.debug ----------------------------
---------------------------- PROCESS ENDED (25050) for package com.aidash.ivms_pro.debug ----------------------------

**Comment by lorenzostudiosok** [comment]
I have the same error, any solution?

  Process: com.orange.blocky.crossy.bridge, PID: 8765
    java.lang.Error: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
    Version '2020.3.34f1 (9a4c9c70452b)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'
    Build fingerprint: 'google/sdk_gphone_x86_64/emu64xa:13/TE1A.220922.033/10836537:userdebug/dev-keys'
    Revision: '0'
    ABI: 'arm64'
    Timestamp: 2023-11-30 20:17:05+0000
    pid: 8765, tid: 8798, name: UnityMain  >>> com.orange.blocky.crossy.bridge <<<
    uid: 10171
    signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
    Cause: null pointer dereference

**Comment by BOBODDY** [comment]
Has any progress been made on this? I'm having the same crash in mapbox version "11.0.0-beta.1" and maps-compose version "0.1.0".
My `MapboxMap` is wrapped in a scrollable `Column` and the crash only happens when the screen is scrolled to the very bottom.

I'm using the standard style.

**Comment by BOBODDY** [comment]
I just retried with mapbox version [11.1.0](https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.1.0) and it seemed to fix my issue.

**Comment by iolandarosavoid** [comment]
I have a crash like this reported in play console recently.

## Environment

- Android OS version: Android 14
- Devices affected: Samsung Galaxy S23 Ultra
- Maps SDK Version: 11.3.0

## Observed behavior and steps to reproduce

Crash happens while Mapbox style is updating the visible layers. We have some custom raster layers but most of the time everything goes ok, this crash only happens sometimes.

I have no specific steps to reproduce the issue.

## Crash Log from Play Console

**[base.apk] com.mapbox.maps.NativeMapImpl.render
SIGSEGV**

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 14290 >>> (...) <<<

backtrace:
  #00  pc 0x000000000083bb10  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #01  pc 0x000000000059b4f0  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #02  pc 0x0000000000757dc8  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #03  pc 0x0000000000564e40  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #04  pc 0x0000000000561d60  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #05  pc 0x0000000000477c74  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #06  pc 0x000000000047250c  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #07  pc 0x00000000004089f0  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/lib/arm64/libmapbox-maps.so (BuildId: d20e455bc3cf4d686acb788d8408120cc946f485)
  #08  pc 0x000000000006ad94  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/oat/arm64/base.odex (art_jni_trampoline+116)
  #09  pc 0x00000000005b98b0  /apex/com.android.art/lib64/libart.so (nterp_helper+4016)
  #10  pc 0x00000000002fba94  /data/app/~~LDRXbg7VBWof_QGEW-wLXQ==/(...)-dQxCfLPFCw-rv-Sre3GDRw==/base.apk (com.mapbox.maps.NativeMapImpl.render+4)
  #11  pc 0x0000000002143158  /memfd:jit-cache (com.mapbox.maps.renderer.MapboxRenderer.render+104)
  #12  pc 0x00000000020b9138  /memfd:jit-cache (com.mapbox.maps.renderer.MapboxRenderThread.draw+840)
  #13  pc 0x000000000211e3b4  /memfd:jit-cache (com.mapbox.maps.renderer.MapboxRenderThread.doFrame+772)
  #14  pc 0x0000000000aff8e8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.view.Choreographer.doCallbacks+1048)
  #15  pc 0x0000000000b00638  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.view.Choreographer.doFrame+2232)
  #16  pc 0x0000000000b89294  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.view.Choreographer$FrameDisplayEventReceiver.run+100)
  #17  pc 0x00000000009b4de4  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Handler.dispatchMessage+68)
  #18  pc 0x00000000009b8894  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loopOnce+980)
  #19  pc 0x00000000009b8424  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.Looper.loop+916)
  #20  pc 0x00000000009b74d8  /data/misc/apexdata/com.android.art/dalvik-cache/arm64/boot.oat (android.os.HandlerThread.run+1000)
  #21  pc 0x000000000033b3a4  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612)
  #22  pc 0x000000000023a5d0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144)
  #23  pc 0x0000000000539a7c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1600)
  #24  pc 0x000000000053942c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallbackWithUffdGc(void*)+8)
  #25  pc 0x00000000000fd0f4  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208)
  #26  pc 0x0000000000096a04  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68)
```

**Comment by kiryldz** [comment]
@iolandarosavoid I am not able to symbolicate your trace most likely because you formatted it. May I ask you to symbolicate it with original error trace following the steps from https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#download-the-unstripped-binary and open the new ticket with symbolicated crash? Thanks

**Comment by jmalanen** [comment]
@iolandarosavoid You mention in your [comment](https://github.com/mapbox/mapbox-maps-android/issues/2052#issuecomment-2056291248) that the Maps SDK Version is 11.3.0. I tested the latest version (1.13.5) of the [app](https://play.google.com/store/apps/details?id=com.voidsoftware.outfitter) but it seems to use an older version of the Maps SDK. Where can I get the app that uses Maps SDK 11.3.0?

Also, what is the frequency of the crash?

> when I ran ndk-stack on the downloaded binary, it didn't write anything to the file

You can get the stack symbolication to work by changing the format slightly (with a simple search & replace operation).

Change the address format from this
`  #00  pc 0x000000000083bb10`

To this (remove the `0x` prefix)
`  #00  pc 000000000083bb10`

**Comment by jmalanen** [comment]
https://play.google.com/apps/test/com.voidsoftware.outfitter/385

@iolandarosavoid I can't access this link so please add my email juha.alanen@mapbox.com to the list.

**Comment by iolandarosavoid** [comment]
@jmalanen Thanks for the feedback. I added your email to the testers list

**Comment by kiryldz** [comment]
@iolandarosavoid this should be fixed in v11.4.0 upcoming next week.

**Comment by angelohenao** [comment]
We have checked using v11.4.0 but still getting fatal signal 11 error when navigating back and forth from various screen with mapbox view

**Comment by AndreKocherSRF** [comment]
We're also experiencing the same crash when navigating between various screens with the Mapbox view.
We also tried it with v11.1.0 but the crash still appears with the same fatal signal 11 error.

**Comment by AkshatDubey10** [comment]
We are also experiencing the same crash on our end when using android auto, have added error logs below

Mapbox Maps SDK Version - 10.18.2
Mapbox Auto Extension Version - 0.5.0


```
libc  F  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 21701 (DefaultDispatch), pid 21657 (ExampleApp)
                  DEBUG  F  #00 pc 000000000005b650  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: 50118287324a156bc7be11d3d940c7be)
                         F  #01 pc 0000000000048f18  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::die()+12) (BuildId: 50118287324a156bc7be11d3d940c7be)
                         F  #02 pc 00000000000498a0  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::ScopedErrorReport::~ScopedErrorReport()+36) (BuildId: 50118287324a156bc7be11d3d940c7be)
                         F  #03 pc 0000000000049d9c  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::reportInvalidChunkState(scudo::AllocatorAction, void*)+120) (BuildId: 50118287324a156bc7be11d3d9
                            40c7be)
                         F  #04 pc 000000000004b830  /apex/com.android.runtime/lib64/bionic/libc.so (scudo::Allocator<scudo::AndroidConfig, &(scudo_malloc_postinit)>::deallocate(void*, scudo::Chunk::Origi
                            n, unsigned long, unsigned long)+316) (BuildId: 50118287324a156bc7be11d3d940c7be)
                         F  #05 pc 00000000003578d8  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/split_config.arm64_v8a.apk!libmapbox-maps.so (offset 0x442000) (Build
                            Id: bf6427639a31f8fa)
                         F  #06 pc 000000000024418c  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/split_config.arm64_v8a.apk!libmapbox-maps.so (offset 0x442000) (Build
                            Id: bf6427639a31f8fa)
                         F  #07 pc 000000000046ee0c  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/split_config.arm64_v8a.apk!libmapbox-maps.so (offset 0x442000) (Build
                            Id: bf6427639a31f8fa)
                         F  #08 pc 0000000000449df8  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/split_config.arm64_v8a.apk!libmapbox-maps.so (offset 0x442000) (Build
                            Id: bf6427639a31f8fa)
                         F  #09 pc 0000000000431c0c  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/split_config.arm64_v8a.apk!libmapbox-maps.so (offset 0x442000) (Build
                            Id: bf6427639a31f8fa)
                         F  #10 pc 00000000002c07a8  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/split_config.arm64_v8a.apk!libmapbox-maps.so (offset 0x442000) (Build
                            Id: bf6427639a31f8fa)
                         F  #11 pc 0000000000294e00  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/split_config.arm64_v8a.apk!libmapbox-maps.so (offset 0x442000) (Build
                            Id: bf6427639a31f8fa)
                         F  #12 pc 00000000001d8478  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/oat/arm64/base.odex (art_jni_trampoline+152)
                         F  #13 pc 000000000232b50c  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.Style.setStyleLayerProperty+300)
                         F  #14 pc 0000000002365c5c  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.extension.style.layers.Layer.updateProperty+220)
                         F  #15 pc 00000000020b5df0  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.extension.style.layers.Layer.setProperty$extension_style_publicRelease+304)
                         F  #16 pc 000000000236f7e0  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.extension.style.layers.generated.SymbolLayer.iconIgnorePlacement+192)
                         F  #17 pc 00000000023c87ec  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.plugin.annotation.generated.PointAnnotationManager.setIconIgnorePlacement+1772)
                         F  #18 pc 000000000237d5f0  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.plugin.annotation.generated.PointAnnotationManager$1.invoke+240)
                         F  #19 pc 00000000023e1ea0  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.plugin.annotation.generated.PointAnnotationManager$1.invoke+96)
                         F  #20 pc 000000000236f654  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.plugin.MapDelegateProviderImpl$$ExternalSyntheticLambda0.onStyleLoaded+196)
                         F  #21 pc 00000000020ee550  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.MapboxMap.getStyle+224)
                         F  #22 pc 00000000021de9bc  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.plugin.MapDelegateProviderImpl.getStyle+172)
                         F  #23 pc 000000000236f380  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.plugin.annotation.generated.PointAnnotationManager.<init>+816)
                         F  #24 pc 000000000237d14c  /memfd:jit-cache (deleted) (offset 0x2000000) (com.mapbox.maps.plugin.annotation.AnnotationPluginImpl.createAnnotationManager+300)
                         F  #25 pc 0000000000780644  /apex/com.android.art/lib64/libart.so (nterp_helper+7636) (BuildId: 1ee2c234829500686eefa384068e67c8)
                         F  #26 pc 000000000286b556  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/oat/arm64/base.vdex (com.mapbox.maps.plugin.annotation.generated.Poin
                            tAnnotationManagerKt.createPointAnnotationManager+14)
                         F  #27 pc 000000000077e8a4  /apex/com.android.art/lib64/libart.so (nterp_helper+52) (BuildId: 1ee2c234829500686eefa384068e67c8)
                         F  #28 pc 0000000001121b6e  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/oat/arm64/base.vdex (auto.utils.map.CarCameraController.addDestinatio
                            nMarker+202)
                         F  #29 pc 000000000077f7c4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 1ee2c234829500686eefa384068e67c8)
                         F  #30 pc 000000000110faae  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/oat/arm64/base.vdex (auto.screens.map.MapScreen$startNavigation$1.inv
                            okeSuspend+178)
                         F  #31 pc 000000000201b650  /memfd:jit-cache (deleted) (offset 0x2000000) (kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith+272)
                         F  #32 pc 000000000091e568  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/oat/arm64/base.odex (kotlinx.coroutines.DispatchedTask.run+1544)
                         F  #33 pc 000000000218ed3c  /memfd:jit-cache (deleted) (offset 0x2000000) (kotlinx.coroutines.internal.LimitedDispatcher$Worker.run+156)
                         F  #34 pc 000000000214ebd8  /memfd:jit-cache (deleted) (offset 0x2000000) (kotlinx.coroutines.scheduling.TaskImpl.run+120)
                         F  #35 pc 000000000237758c  /memfd:jit-cache (deleted) (offset 0x2000000) (kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely+108)
                         F  #36 pc 00000000020f2e88  /memfd:jit-cache (deleted) (offset 0x2000000) (kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker+1080)
                         F  #37 pc 000000000077f7c4  /apex/com.android.art/lib64/libart.so (nterp_helper+3924) (BuildId: 1ee2c234829500686eefa384068e67c8)
                         F  #38 pc 0000000003104e78  /data/app/~~_Hh9k9L-qRtO_PuzPgg65w==/com.ExampleApp-U_R66U7ATLqkpLegGlHhLg==/oat/arm64/base.vdex (kotlinx.coroutines.scheduling.CoroutineScheduler
                            $Worker.run+0)
                         F  #39 pc 0000000000362774  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: 1ee2c234829500686eefa384068e67c8)
                         F  #40 pc 000000000034def0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+132) (BuildId: 1ee2
                            c234829500686eefa384068e67c8)
                         F  #41 pc 0000000000943e28  /apex/com.android.art/lib64/libart.so (_ZN3art9ArtMethod14InvokeInstanceILc86ETpTncJEEENS_6detail12ShortyTraitsIXT_EE4TypeEPNS_6ThreadENS_6ObjPtrINS_6m
                            irror6ObjectEEEDpNS3_IXT0_EE4TypeE+60) (BuildId: 1ee2c234829500686eefa384068e67c8)
                         F  #42 pc 000000000063ebd4  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1344) (BuildId: 1ee2c234829500686eefa384068e67c8)
                         F  #43 pc 00000000000c3644  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+208) (BuildId: 50118287324a156bc7be11d3d940c7be)
                         F  #44 pc 000000000005cfa4  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+68) (BuildId: 50118287324a156bc7be11d3d940c7be)
```

**Comment by oppware** [comment]
I still get the same error when changing from a 3D style to a 2D style.
Had the error in android emulator and real android devices, from older mapbox_maps_flutter versions to the latest 2.11.0.
Is there any update on this?
