### ISSUE TITLE
coordinateBoundsForCameraUnwrapped does not work correctly

### ISSUE THREAD

**Issue by ystsoi** [mapbox/mapbox-maps-android#2230]
## Environment

- Maps SDK Version: 11.0.0

## Observed behavior and steps to reproduce

For `mapView.mapboxMap.coordinateBoundsForCameraUnwrapped(CameraOptions.Builder().center(Point.fromLngLat(180.0, 0.0)).bearing(0.0).pitch(0.0).zoom(2.0).build())`, the west and east of the returned bounds are around -122 and 122.

## Expected behavior

For `mapView.mapboxMap.coordinateBoundsUnwrapped(for: .init(center: .init(latitude: 0, longitude: 180), zoom: 2, bearing: 0, pitch: 0))` using the iOS version, the west and east of the returned bounds are around -239 and -121.

**Comment by baleboy** [comment]
This should be resolved in v11.0.0-beta.1, to be released next week

**Comment by jush** [comment]
https://github.com/mapbox/mapbox-maps-android/releases/tag/v11.1.0-beta.1 is now released. Please re-open if issue still occurs.
