### ISSUE TITLE
ConcurrentModificationException crash when properties changed shortly after annotation is created

### ISSUE THREAD

**Issue by e-hartig** [mapbox/mapbox-maps-android#383]
## Environment

- Android OS version: All
- Devices affected: All
- Maps SDK Version: 10.0.0-beta.12 - beta.20

## Observed behavior and steps to reproduce

If the properties of an annotation are changed quickly after an annotation is created, the applicaton crashes with a ConcurrentModificationException.

It is easy to reproduce this crash by adding this click listener to the CircleAnnotationActivity or elsewhere within the Mapbox Android sample app and then clicking the map a few times:
```
mapView?.getMapboxMap()?.addOnMapClickListener() { point ->
    val pointAnnotationPluginImpl = mapView.annotations.createPointAnnotationManager(mapView)
    // Create the annotation
    val annotation = pointAnnotationPluginImpl.create(PointAnnotationOptions().withDraggable(false)
        .withPoint(point)
        .withTextAnchor(TextAnchor.BOTTOM)
        .withTextColor(Color.BLUE)
        .withTextSize(12.0)
        .withTextField("Please don't crash!"))
    Thread.sleep(1)
    // Update its properties shortly after creation - often causes crash
    annotation.textField = "We're an enterprise customer!"
    annotation.textRotate = Math.random() * 180
    true
}
```

## Expected behavior

No crash.

## Notes / preliminary analysis

AnnotationManagerImpl.updateSource calls `geoJsonSource.featureCollection()` ([line 364](https://github.com/mapbox/mapbox-maps-android/blob/d092c5463172f6fe2033eb4c16925509d086f767/plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt#L364)) which asynchronously iterates through the properties of the annotation feature.  If the set of properties on the annotation is updated by another thread during this async iteration, a ConcurrentModificationException is raised.

If `featureCollection` must be asynchronous, maybe it should act on an immutable copy of the feature's properties.

## Additional links and references

Stack trace:
```
2021-06-02 16:36:07.986 15470-15532/com.example.mapboxsample E/AndroidRuntime: FATAL EXCEPTION: STYLE_WORKER
    Process: com.example.mapboxsample, PID: 15470
    java.util.ConcurrentModificationException
        at com.google.gson.internal.LinkedTreeMap$LinkedTreeMapIterator.nextNode(LinkedTreeMap.java:544)
        at com.google.gson.internal.LinkedTreeMap$EntrySet$1.next(LinkedTreeMap.java:568)
        at com.google.gson.internal.LinkedTreeMap$EntrySet$1.next(LinkedTreeMap.java:566)
        at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:758)
        at com.google.gson.internal.bind.TypeAdapters$29.write(TypeAdapters.java:698)
        at com.google.gson.internal.bind.TypeAdapters$35$1.write(TypeAdapters.java:890)
        at com.mapbox.geojson.Feature$GsonTypeAdapter.write(Feature.java:568)
        at com.mapbox.geojson.Feature$GsonTypeAdapter.write(Feature.java:497)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:97)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:61)
        at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.write(FeatureCollection.java:328)
        at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.write(FeatureCollection.java:278)
        at com.google.gson.Gson.toJson(Gson.java:704)
        at com.google.gson.Gson.toJson(Gson.java:683)
        at com.google.gson.Gson.toJson(Gson.java:638)
        at com.google.gson.Gson.toJson(Gson.java:618)
        at com.mapbox.geojson.FeatureCollection.toJson(FeatureCollection.java:223)
        at com.mapbox.maps.extension.style.utils.TypeUtilsKt.toValue(TypeUtils.kt:306)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.toPropertyValue(GeoJsonSource.kt:559)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.access$toPropertyValue(GeoJsonSource.kt:29)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource$applyGeoJsonData$$inlined$apply$lambda$1.run(GeoJsonSource.kt:571)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by tobrun** [comment]
Thank you for the report @e-hartig, been trying to reproduce without luck so far.

**Comment by e-hartig** [comment]
@tobrun Thanks for looking into it! Depending on the speed of your device/emulator, the Thread.sleep in my example code may have to be increased or removed.  On my x86 emulator, the 1ms sleep reproduces the issue within 10 clicks on the map.

**Comment by cramptonism** [comment]
Took 20-30 clicks on a Pixel 5 with Thread.sleep(1) for me, on 6120ff31230acd8a2bcaac469668abb635db6dea of the sample app. Worth noting a couple of the annotations never received the text update and remained as "Please don't crash".

**Comment by Chaoba** [comment]
@e-hartig @cramptonism I have tried to reproduce this issue wite beta.rc1 and can't make it. Guess  this was fixed by async geojson parsing feature. Can you try it again on beta.rc1?

**Comment by e-hartig** [comment]
@Chaoba I can still reproduce the issue on beta.rc1.  I came up with a code snippet to reproduce the issue more quickly.  This crashed in 1 click reliably on an emulator and on a real device:

```
mapView?.getMapboxMap()?.addOnMapClickListener() { point ->
    val pointAnnotationPluginImpl = mapView.annotations.createPointAnnotationManager(mapView)

    val annotation = pointAnnotationPluginImpl.create(
        PointAnnotationOptions().withDraggable(false)
            .withPoint(point)
            .withTextAnchor(TextAnchor.BOTTOM)
            .withTextColor(Color.BLUE)
            .withTextSize(12.0)
            .withTextField("Please don't crash!")
    )

    for (i in 0..100) {
        // Adding properties to the jsonObject of the annotation changes the
        // modCount of the object. If the modCount changes while data.toPropertyValue()
        // is running in GeoJsonSource.applyGeoJsonData(), crash occurs.
        annotation.jsonObject.addProperty("test$i", "Property")
        Thread.sleep(0,2000)
    }

    true
}
```

**Comment by Chaoba** [comment]
@e-hartig Thanks for your example and I can reproduce it now. This reminds me that we shouldn't expose `jsonObject` to users and only allow users to update properties by provides methods. I have updated a [branch](https://github.com/mapbox/mapbox-maps-android/tree/kl-annotation-property), can you verify whether this issue can be reproduced in that branch?

**Comment by e-hartig** [comment]
@Chaoba I haven't been able to set aside the time to get that branch to run locally (had some build issues), but from checking out the code I would expect that it would solve the issue.
