### ISSUE TITLE
Black screen on some devices after v10.0.0

### ISSUE THREAD

**Issue by nadavmos** [mapbox/mapbox-maps-android#976]
## Environment

- Android OS version: 6.0.1
- Devices affected: SIBO Q896S, GLES: Imagination Technologies, PowerVR SGX 544MP, OpenGL ES 2.0 build 1.14@3793329
- Maps SDK Version: 10.2.0-rc.1

## Observed behavior and steps to reproduce

Create app with basic map as described in the documentation. 

![device-2021-12-12-174154](https://user-images.githubusercontent.com/2006268/145719001-d3109e71-722a-4c2e-a8c0-e4d624e050c0.png)

## Expected behavior

Map loads. 

## Notes / preliminary analysis

mapbox up to v10.0.0  works on these devices.
starting mapbox v10.1.0-beta.1 the black screen is shown and map doesn't load.
logs have some hints about egl error:

**v10.0.0:** (working)
 
 I/MapboxCommonSDK: Loaded
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/Mbgl-FontUtils: Couldn't map font family for local ideograph, using sans-serif instead
I/art: Thread[1,tid=30204,Native,Thread*=0xb4df6500,peer=0x73e93000,"main"] recursive attempt to load library "/data/app/com.example.myapplication-2/base.apk!/lib/armeabi-v7a/libmapbox-maps.so"
I/art: Thread[1,tid=30204,Native,Thread*=0xb4df6500,peer=0x73e93000,"main"] recursive attempt to load library "/data/app/com.example.myapplication-2/base.apk!/lib/armeabi-v7a/libmapbox-maps.so"
I/art: Thread[1,tid=30204,Native,Thread*=0xb4df6500,peer=0x73e93000,"main"] recursive attempt to load library "/data/app/com.example.myapplication-2/base.apk!/lib/armeabi-v7a/libmapbox-maps.so"
I/art: Thread[1,tid=30204,Native,Thread*=0xb4df6500,peer=0x73e93000,"main"] recursive attempt to load library "/data/app/com.example.myapplication-2/base.apk!/lib/armeabi-v7a/libmapbox-maps.so"
I/art: Thread[1,tid=30204,Native,Thread*=0xb4df6500,peer=0x73e93000,"main"] recursive attempt to load library "/data/app/com.example.myapplication-2/base.apk!/lib/armeabi-v7a/libmapbox-maps.so"
I/MapboxReachability: Application permission for ACCESS_NETWORK_STATE granted
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.app.JobIntentService$JobServiceEngineImpl>
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.app.JobIntentService$JobServiceEngineImpl>
D/libEGL: loaded /vendor/lib/egl/libEGL_POWERVR_SGX544_115.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so
I/IMGSRV: Dram size is 2018 MB
    Secure level is 1
I/IMGSRV: Allocate 4096 Bytes uncached memory via ion heap type DMA successfully, iUsage = 0x10000000
I/IMGSRV: Dram size is 2018 MB
    Secure level is 1
I/OpenGLRenderer: Initialized EGL, version 1.4
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
I/Mbgl-EGLConfigChooser: In emulator: false
D/Mbgl-EglCore: EGLContext created, client version 2
I/maps: Using OpenGL render backend
I/maps: {MapboxRenderThr}[General]: GPU Identifier: PowerVR SGX 544MP
W/maps: {MapboxRenderThr}[OpenGL]: Not using Vertex Array Objects
D/CrashJobIntentService: onHandleWork
 
**v10.2.0-rc.1** (broken)

I/MapboxCommonSDK: Loaded
I/maps: Using Mapbox Core Maps SDK v10.2.0@6710299518 and Mapbox Common SDK v21.0.0-rc.2
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
I/Mbgl-FontUtils: Couldn't map font family for local ideograph, using sans-serif instead
I/MapboxReachability: Application permission for ACCESS_NETWORK_STATE granted
D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.app.JobIntentService$JobServiceEngineImpl>
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.app.JobIntentService$JobServiceEngineImpl>
D/libEGL: loaded /vendor/lib/egl/libEGL_POWERVR_SGX544_115.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX544_115.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX544_115.so
I/IMGSRV: Dram size is 2018 MB
    Secure level is 1
I/IMGSRV: Allocate 4096 Bytes uncached memory via ion heap type DMA successfully, iUsage = 0x10000000
I/IMGSRV: Dram size is 2018 MB
I/IMGSRV: Secure level is 1
I/OpenGLRenderer: Initialized EGL, version 1.4
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
I/Mbgl-EGLConfigChooser: In emulator: false
W/Mbgl-EGLConfigChooser: Chosen config is not conformant.
E/Mbgl-EglCore: eglCreateContext: EGL error: 0x3005
E/libEGL: eglQueryContext:815 error 3006 (EGL_BAD_CONTEXT)
D/Mbgl-EglCore: EGLContext created, client version 0
E/Mbgl-RenderThread: EGL was not configured, please check logs above.
D/CrashJobIntentService: onHandleWork

**Comment by polly3223** [comment]
I confirm this bug: works as expected on 10.0.0 and black screen on 10.1.0.

Physical device:  HUAWEY Y5 Prime 2018
Android Version: 8.1.0

App compiled with:
minSdkVersion 24
targetSdkVersion 31

Ask me if you need other information to reproduce.

**Comment by yunikkk** [comment]
Hi @nadavmos, @polly3223 thanks for the report. Could you check that two different fixes works on your devices? 
- With the latest 10.1.0 release you should be able to apply workaround by setting different MapInitOptions.antialiasingSampleCount, e.g. 
```
    mapView = MapView(
      inflater.context,
      MapInitOptions(
        inflater.context,
        antialiasingSampleCount = 4,
      )
    )
```
- Another fix that would be nice to check is published with snapshot `10.2.0-beta.1-yds-fix-egl-attributes-SNAPSHOT`. Details on how to setup snapshot maven repo : https://github.com/mapbox/mapbox-maps-android/blob/main/DEVELOPING.md#use-snapshot-releases-in-your-app.

**Comment by polly3223** [comment]
On my device placing mapbox:mapbox_mapAntialiasingSampleCount="4" in the XML solves the issue with version 10.1.0.

With 10.2.0-beta.1-yds-fix-egl-attributes-SNAPSHOT the issue is solved without putting the mapbox:mapbox_mapAntialiasingSampleCount="4" in the XML.

I will use the solution 1 since it's the production build, when 10.2.0 I will remove the line from the XML.

Thank you so much @yunikkk !!

**Comment by nadavmos** [comment]
> * 10.2.0-beta.1-yds-fix-egl-attributes-SNAPSHOT

Confirmed 10.2.0-beta.1-yds-fix-egl-attributes-SNAPSHOT fixes the issue on my device

**Comment by kiryldz** [comment]
@polly3223 @nadavmos thanks for helping to test it out.
Fix is available as part of https://github.com/mapbox/mapbox-maps-android/releases/tag/android-v10.2.0 release.

**Comment by AndriiYanechko** [comment]
Unfortunately still happening for me.

- Android OS version: 12
- Devices affected: **Samsung S10**, Android Emulator API 33 arm
- Maps SDK Version: `10.9.0` (latest)

This bug wasn't happening on the v9 versions, but currently I'm migrating to the latest version.

P.S. the `app:mapbox_mapAntialiasingSampleCount="4"` not helping in my case.

Please take a look at following video:

https://user-images.githubusercontent.com/112496967/199602545-6b23c2da-8a74-4270-93d6-de811d213a6c.mp4

**Comment by AndriiYanechko** [comment]
Still happens on `10.9.0`. Only for the first installation.

https://user-images.githubusercontent.com/112496967/206242655-39b1a8a0-767e-4093-af28-5f1dbef9e433.mp4

**Comment by taq** [comment]
I'm updated and facing a similar issue after the following steps:

- Map activity loaded, ok
- Going to another activity, ok
- Returning to the map activity, closing the other activity, ok
- Pressing the power button to turn off the screen 
- Pressing the power button to turn on the screen 
- Map activiy is ok
- Going to another activity, ok
- Returning to the map activity, the map is all black

I tried every possible things all day long but can't fix that. Is there any way to get some event to show why the map is black after the off/on/other activity thing?

**Comment by yunikkk** [comment]
@taq hi, we'll need more details to be able to help - Maps version, device, OS etc. Anything suspicious in the logcat when map turns black? I suggest you to file a new issue since this one was about specific issue with GLES settings.

**Comment by taq** [comment]
Hey @yunikkk ! Got some more info here. We have some devices where the map is not black. Comparing them, the big difference: the device who has a screen lock works ok, the device I was using when I created the comment above goes back to the app after the power button is pressed to turn on the screen! Seems that there are some differences on the Android app life cycle with those behaviours, something related with the saved state, perhaps?

So:

- Power button pressed, off, power button pressed, on, screen locked, slide to unlock, app comes back with map ok
- Power button pressed, off, power button pressed, on, **no lock screen**, app returned with black map

**Comment by sascha-kaleidoscode** [comment]
Any news on that? Did you solve it? I'm running into the same issue in a react-native project with @rnmapbox/mapbox. MapBox version is 10.12.1.

**Comment by yunikkk** [comment]
@sascha-kaleidoscode if the similar issue reproduces for you please submit a new ticket with details, the original one was bug with antialiasing settings and was fixed.

**Comment by taq** [comment]
@sascha-kaleidoscode I just enabled the device lock screen, was the easier and faster way to solve it.

**Comment by groom7** [comment]
> [@sascha-kaleidoscode](https://github.com/sascha-kaleidoscode) if the similar issue reproduces for you please submit a new ticket with details, the original one was bug with antialiasing settings and was fixed.

Hello. Could you please tell me if you were able to solve the black screen problem?
